version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: stationSki
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - backend-network

  spring:
    image: lobnasakli/gestion-station-ski:latest
    ports:
      - "8089:8089"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true
    volumes:
      - spring_data:/app/data
    depends_on:
      - mysql
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
volumes:
  angular_data:
  mysql_data:
  mysql_config:
  spring_data: