global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.33.10:9090']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'  # Specify the metrics path here
    static_configs:
        - targets: [ '192.168.33.10:8080' ]

  - job_name: 'spring-actuator'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['192.168.33.10:8089']
